package stats

var TeamColors = map[string][]string {
	"atl": {"e03a3e", "c1d32f", "26282a"},
	"bkn": {},
	"bos": {"008348", "bb9753", ""},
	"cha": {},
	"chi": {},
	"cle": {"6f263d", "ffb81c", "041e42"},
	"dal": {},
	"den": {},
	"det": {},
	"gsw": {},
	"hou": {},
	"ind": {},
	"lac": {},
	"lal": {},
	"mem": {},
	"mia": {},
	"mil": {},
	"min": {},
	"nop": {},
	"nyk": {},
	"okc": {},
	"orl": {},
	"phi": {},
	"phx": {},
	"por": {},
	"sac": {},
	"sas": {},
	"tor": {},
	"uta": {},
	"was": {},
}