package stats

type TeamMap struct {
	Name						string				`json:"name"`
	City            string        `json:"city"`
	Code						string				`json:"code"`
	Abv             string        `json:"abv"`
	Division				string				`json:"division"`
	Conference			string				`json:"conference"`
}


var tm = map[int]*TeamMap{
	1610612738: &TeamMap{
		Name: "Boston Celtics",
		City: "Boston",
		Code: "BOS",
		Abv: "Celtics",
		Division: "Atlantic",
		Conference: "Eastern",
	},
	1610612751: &TeamMap{
		Name: "Brooklyn Nets",
		City: "Brooklyn",
		Code: "BKN",
		Abv: "Nets",
		Division: "Atlantic",
		Conference: "Eastern",
	},
	1610612752: &TeamMap{
		Name: "New York Knicks",
		City: "New York",
		Code: "NYK",
		Abv: "Knicks",
		Division: "Atlantic",
		Conference: "Eastern",
	},
	610612755: &TeamMap{
		Name: "Philadelphia 76ers",
		City: "Philadelphia",
		Code: "PHI",
		Abv: "76ers",
		Division: "Atlantic",
		Conference: "Eastern",
	},
	1610612761: &TeamMap{
		Name: "Toronto Raptors",
		City: "Toronto",
		Code: "TOR",
		Abv: "Raptors",
		Division: "Atlantic",
		Conference: "Eastern",
	},
	1610612741: &TeamMap{
		Name: "Chicago Bulls",
		City: "Chicago",
		Code: "CHI",
		Abv: "Bulls",
		Division: "Central",
		Conference: "Eastern",
	},
	1610612739: &TeamMap{
		Name: "Cleveland Cavaliers",
		City: "Cleveland",
		Code: "CLE",
		Abv: "Cavaliers",
		Division: "Central",
		Conference: "Eastern",
	},
	1610612765: &TeamMap{
		Name: "Detroit Pistons",
		City: "Detroit",
		Code: "DET",
		Abv: "Pistons",
		Division: "Atlantic",
		Conference: "Eastern",
	},
	1610612754: &TeamMap{
		Name: "Indiana Pacers",
		City: "Indiana",
		Code: "IND",
		Abv: "Pacers",
		Division: "Atlantic",
		Conference: "Eastern",
	},
	1610612749: &TeamMap{
		Name: "Milwaukee Bucks",
		City: "Milwaukee",
		Code: "MIL",
		Abv: "Bucks",
		Division: "Atlantic",
		Conference: "Eastern",
	},
	1610612737: &TeamMap{
		Name: "Atlanta Hawks",
		City: "Atlanta",
		Code: "ATL",
		Abv: "Hawks",
		Division: "Southeast",
		Conference: "Eastern",
	},
	1610612766: &TeamMap{
		Name: "Charlotte Hornets",
		City: "Charlotte",
		Code: "CHA",
		Abv: "Hornets",
		Division: "Southeast",
		Conference: "Eastern",
	},
	1610612748: &TeamMap{
		Name: "Miami Heat",
		City: "Miami",
		Code: "MIA",
		Abv: "Heat",
		Division: "Southeast",
		Conference: "Eastern",
	},
	1610612753: &TeamMap{
		Name: "Orlando Magic",
		City: "Orlando",
		Code: "ORL",
		Abv: "Magic",
		Division: "Southeast",
		Conference: "Eastern",
	},
	1610612764: &TeamMap{
		Name: "Washington Wizards",
		City: "Washington",
		Code: "WAS",
		Abv: "Wizards",
		Division: "Southeast",
		Conference: "Eastern",
	},
	1610612743: &TeamMap{
		Name: "Denver Nuggets",
		City: "Denver",
		Code: "DEN",
		Abv: "Nuggets",
		Division: "Northwest",
		Conference: "Western",
	},
	1610612750: &TeamMap{
		Name: "Minnesota Timberwolves",
		City: "Minnesota",
		Code: "MIN",
		Abv: "Timberwolves",
		Division: "Northwest",
		Conference: "Western",
	},
	1610612760: &TeamMap{
		Name: "Oklahoma City Thunder",
		City: "Oklahoma City",
		Code: "OKC",
		Abv: "Thunder",
		Division: "Northwest",
		Conference: "Western",
	},
	1610612757: &TeamMap{
		Name: "Portland Trailblazers",
		City: "Portland",
		Code: "POR",
		Abv: "Trailblazers",
		Division: "Northwest",
		Conference: "Western",
	},
	1610612762: &TeamMap{
		Name: "Utah Jazz",
		City: "Utah",
		Code: "UTA",
		Abv: "Jazz",
		Division: "Northwest",
		Conference: "Western",
	},
	1610612744: &TeamMap{
		Name: "Golden State Warriors",
		City: "Golden State",
		Code: "GSW",
		Abv: "Warriors",
		Division: "Pacific",
		Conference: "Western",
	},
	1610612746: &TeamMap{
		Name: "LA Clippers",
		City: "LA",
		Code: "LAC",
		Abv: "Clippers",
		Division: "Pacific",
		Conference: "Western",
	},
	1610612747: &TeamMap{
		Name: "Los Angeles Lakers",
		City: "Los Angeles",
		Code: "LAL",
		Abv: "Lakers",
		Division: "Pacific",
		Conference: "Western",
	},
	1610612756: &TeamMap{
		Name: "Phoenix Suns",
		City: "Phoenix",
		Code: "PHX",
		Abv: "Suns",
		Division: "Pacific",
		Conference: "Western",
	},
	1610612758: &TeamMap{
		Name: "Sacremento Kings",
		City: "Sacremento",
		Code: "SAC",
		Abv: "Kings",
		Division: "Pacific",
		Conference: "Western",
	},
	1610612742: &TeamMap{
		Name: "Dallas Mavericks",
		City: "Dallas",
		Code: "DAL",
		Abv: "Mavericks",
		Division: "Southwest",
		Conference: "Western",
	},
	1610612745: &TeamMap{
		Name: "Houston Rockets",
		City: "Houston",
		Code: "HOU",
		Abv: "Rockets",
		Division: "Southwest",
		Conference: "Western",
	},
	1610612763: &TeamMap{
		Name: "Memphis Grizzlies",
		City: "Memphis",
		Code: "MEM",
		Abv: "Grizzlies",
		Division: "Southwest",
		Conference: "Western",
	},
	1610612740: &TeamMap{
		Name: "New Orleans Pelicans",
		City: "New Orleans",
		Code: "NOP",
		Abv: "Pelicans",
		Division: "Southwest",
		Conference: "Western",
	},
	1610612759: &TeamMap{
		Name: "San Antonio Spurs",
		City: "San Antonio",
		Code: "SAS",
		Abv: "Spurs",
		Division: "Southwest",
		Conference: "Western",
	},
}
